<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ProductCodeWSWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ProductCodeWSWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ProductCodeWSWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://web/">
    <import location="http://localhost:8080/NewsApp-war/ProductCodeWS?WSDL" namespace="http://web/"/>
    <plnk:partnerLinkType name="ProductCodeWSLinkType">
        <plnk:role name="ProductCodeWSRole" portType="ns:ProductCodeWS"/>
    </plnk:partnerLinkType>
</definitions>
