<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TiendaWSWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/TiendaWSWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/TiendaWSWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://web/">
    <import location="http://localhost:8080/NewsApp-war/TiendaWS?WSDL" namespace="http://web/"/>
    <plnk:partnerLinkType name="TiendaWSLinkType">
        <plnk:role name="TiendaWSRole" portType="ns:TiendaWS"/>
    </plnk:partnerLinkType>
</definitions>
